'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {generate,MODES}=require('./engines');
const payment=require('./payment'),email=require('./email'),db=require('./db');
const ROOT=path.join(__dirname,'public'),PORT=Number(process.env.PORT||3000),ADMIN_KEY=process.env.ADMIN_KEY||'CHANGE_ME';
const TTL=Number(process.env.ORDER_TTL_MINUTES||30)*60000;const buckets=new Map(),WINDOW=60000,LIMIT=Number(process.env.RATE_LIMIT_PER_MINUTE||60);
function id(){return 'L15-'+crypto.randomBytes(9).toString('hex').toUpperCase()}function token(){return crypto.randomBytes(24).toString('hex')}function hash(s){return crypto.createHash('sha256').update(s).digest('hex')}
function headers(res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");if(process.env.NODE_ENV==='production')res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains')}
function json(res,s,p){headers(res);res.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(p))}
function read(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>200000){reject(Object.assign(new Error('Corpo muito grande'),{status:413}));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(Object.assign(new Error('JSON inválido'),{status:400}))}});req.on('error',reject)})}
function limited(req){const key=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0];const now=Date.now();let b=buckets.get(key);if(!b||now-b.t>WINDOW){b={t:now,n:0};buckets.set(key,b)}b.n++;return b.n>LIMIT}
function expire(o){if(o.status==='PENDING'&&Date.now()-Date.parse(o.createdAt)>TTL){o.status='EXPIRED';o.expiredAt=new Date().toISOString();return true}return false}
function auth(req){const p=String(req.headers['x-admin-key']||'');if(!p||ADMIN_KEY==='CHANGE_ME')return false;const a=Buffer.from(p),b=Buffer.from(ADMIN_KEY);return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function safeFile(url){const u=decodeURIComponent((url||'/').split('?')[0]);const reqp=u==='/'?'/index.html':u;const f=path.normalize(path.join(ROOT,reqp));const rel=path.relative(ROOT,f);return rel.startsWith('..')||path.isAbsolute(rel)?null:f}
function mime(ext){return ({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'})[ext]||'application/octet-stream'}
async function confirmMP(o){if(!o.payment?.externalId && !o.payment?.orderId)return false;if(expire(o)){await db.saveOrder(o);return false}let status='unknown',detail='';if(o.payment.orderId){const ord=await payment.getOrder(o.payment.orderId);if(String(ord.external_reference||'')!==o.id)throw new Error('Referência externa incompatível');status=ord.status||'unknown';detail=ord.status_detail||'';if(status==='processed' && detail==='accredited'){o.status='PAID';o.paidAt=o.paidAt||new Date().toISOString();o.payment.rawStatus=status;o.payment.rawStatusDetail=detail;await db.saveOrder(o);await db.addEvent('PAYMENT_CONFIRMED',o,{provider:'mercadopago'});return true}}else{const pay=await payment.getPayment(o.payment.externalId);if(String(pay.external_reference||'')!==o.id)throw new Error('Referência externa incompatível');status=pay.status||'unknown';detail=pay.status_detail||'';if(status==='approved'){o.status='PAID';o.paidAt=o.paidAt||new Date().toISOString();o.payment.rawStatus=status;o.payment.rawStatusDetail=detail;await db.saveOrder(o);await db.addEvent('PAYMENT_CONFIRMED',o,{provider:'mercadopago'});return true}}o.payment.rawStatus=status;o.payment.rawStatusDetail=detail;await db.saveOrder(o);return false}
const revealLocks=new Map();
async function reveal(o){if(o.status!=='PAID')return null;if(o.games)return o.games;if(revealLocks.has(o.id))return revealLocks.get(o.id);const work=(async()=>{o.games=generate(o.mode,o.quantity);o.generatedAt=new Date().toISOString();await db.saveOrder(o);await db.addEvent('GAMES_GENERATED',o,{mode:o.mode,quantity:o.quantity});try{o.emailResult=await email.sendGames({to:o.email,mode:o.mode,quantity:o.quantity,games:o.games,orderId:o.id});await db.saveOrder(o)}catch(e){o.emailResult={sent:false,error:e.message};await db.saveOrder(o)}return o.games})().finally(()=>revealLocks.delete(o.id));revealLocks.set(o.id,work);return work}
async function main(req,res){
 try{
  if(req.url.startsWith('/api/')&&limited(req))return json(res,429,{error:'Muitas requisições. Tente novamente.'});
  await db.expirePending(TTL);
  if(req.method==='GET'&&req.url==='/api/health')return json(res,200,{ok:true,version:'16.2.0',database:db.dbMode(),paymentProvider:payment.configured()?'mercadopago':'sandbox',modalities:Object.keys(MODES)});
  if(req.method==='POST'&&req.url==='/api/orders'){
   const b=await read(req),mode=String(b.mode||''),quantity=Number(b.quantity);
   if(!MODES[mode])return json(res,400,{error:'Modalidade inválida.'});if(![1,5].includes(quantity))return json(res,400,{error:'Quantidade inválida.'});
   const idem=String(req.headers['x-idempotency-key']||'');const existingId=await db.getOrderByIdempotency(idem);if(existingId){const existing=await db.getOrder(existingId);if(existing)return json(res,200,publicOrder(existing,undefined))}
   const access=token(),o={id:id(),accessHash:hash(access),mode,quantity,price:quantity===1?1:3,email:null,status:'PENDING',createdAt:new Date().toISOString(),payment:null,games:null};
   o.payment=await payment.createPixOrder(o);await db.saveOrder(o);if(idem)await db.saveIdempotency(idem,o.id);await db.addEvent('ORDER_CREATED',o,{mode,quantity,price:o.price});return json(res,201,publicOrder(o,access));
  }
  if(req.method==='GET'&&req.url.startsWith('/api/orders/')){const oid=req.url.split('/').pop(),o=await db.getOrder(oid);if(!o)return json(res,404,{error:'Pedido não encontrado'});if(o.status==='PENDING'&&payment.configured()){try{await confirmMP(o)}catch(e){console.warn('Falha ao atualizar pagamento:',e.message)}}return json(res,200,{id:o.id,mode:o.mode,quantity:o.quantity,price:o.price,status:o.status,generatedAt:o.generatedAt,hasGames:!!o.games,emailSent:!!o.emailResult?.sent,paymentMode:o.payment?.mode})}
  if(req.method==='POST'&&req.url==='/api/sandbox/confirm'){if(payment.configured())return json(res,403,{error:'Sandbox desativado'});const b=await read(req),o=await db.getOrder(b.id);if(!o)return json(res,404,{error:'Pedido não encontrado'});if(o.status!=='PENDING')return json(res,409,{error:'Pedido não está pendente'});if(expire(o)){await db.saveOrder(o);return json(res,410,{error:'Pedido expirado'})}o.status='PAID';o.paidAt=new Date().toISOString();await db.saveOrder(o);await db.addEvent('PAYMENT_CONFIRMED',o,{provider:'sandbox'});return json(res,200,{id:o.id,status:o.status})}
  if(req.method==='POST'&&req.url.startsWith('/api/webhooks/mercadopago')){if(!payment.configured()||!payment.webhookConfigured())return json(res,503,{error:'Mercado Pago/webhook não configurado'});const b=await read(req),u=new URL(req.url,'http://localhost'),pid=b?.data?.id||b?.id||u.searchParams.get('data.id');if(!payment.verifyWebhookSignature({xSignature:req.headers['x-signature'],xRequestId:req.headers['x-request-id'],dataId:pid}))return json(res,401,{error:'Assinatura inválida'});const o=await db.findOrderByPaymentId(pid);if(o)await confirmMP(o);return json(res,200,{received:true})}
  if(req.method==='POST'&&req.url==='/api/reveal'){const b=await read(req),o=await db.getOrder(b.id);if(!o)return json(res,404,{error:'Pedido não encontrado'});if(hash(String(b.accessToken||''))!==o.accessHash)return json(res,401,{error:'Acesso inválido'});if(o.status!=='PAID'&&payment.configured())await confirmMP(o);if(o.status!=='PAID')return json(res,403,{error:'Pagamento ainda não confirmado'});const games=await reveal(o);return json(res,200,{id:o.id,status:o.status,mode:o.mode,quantity:o.quantity,generatedAt:o.generatedAt,games,emailSent:!!o.emailResult?.sent})}
  if(req.method==='POST'&&req.url==='/api/email'){
   const b=await read(req),o=await db.getOrder(b.id);if(!o)return json(res,404,{error:'Pedido não encontrado'});
   if(hash(String(b.accessToken||''))!==o.accessHash)return json(res,401,{error:'Acesso inválido'});
   if(o.status!=='PAID'||!o.games)return json(res,403,{error:'O pedido ainda não está liberado.'});
   const em=String(b.email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(em))return json(res,400,{error:'E-mail inválido.'});
   o.email=em;
   try{o.emailResult=await email.sendGames({to:o.email,mode:o.mode,quantity:o.quantity,games:o.games,orderId:o.id});await db.saveOrder(o);await db.addEvent('EMAIL_REQUESTED',o,{sent:!!o.emailResult?.sent});return json(res,200,{id:o.id,sent:!!o.emailResult?.sent})}
   catch(e){o.emailResult={sent:false,error:e.message};await db.saveOrder(o);return json(res,502,{error:e.message||'Falha no envio de e-mail.'})}
  }
  if(req.method==='GET'&&req.url==='/api/admin/summary'){if(!auth(req))return json(res,401,{error:'Não autorizado'});const s=await db.summary();return json(res,200,{version:'16.2.0',database:db.dbMode(),provider:payment.configured()?'mercadopago':'sandbox',totalOrders:s.total,pending:s.pending,paid:s.paid,released:s.released,revenue:s.revenue,orders:s.orders})}
  if(req.method==='GET'&&req.url==='/api/admin/events'){if(!auth(req))return json(res,401,{error:'Não autorizado'});return json(res,200,await db.listEvents(200))}
  const f=safeFile(req.url);if(req.method==='GET'&&f&&fs.existsSync(f)){res.writeHead(200,{'Content-Type':mime(path.extname(f)),'Cache-Control':'no-cache'});return fs.createReadStream(f).pipe(res)}
  return json(res,404,{error:'Não encontrado'});
 }catch(e){console.error(e);return json(res,e.status||500,{error:e.message||'Erro interno'})}
}
function publicOrder(o,access){const out={id:o.id,mode:o.mode,quantity:o.quantity,price:o.price,status:o.status,paymentMode:o.payment?.mode,payment:{mode:o.payment?.mode,qrCode:o.payment?.qrCode,qrCodeBase64:o.payment?.qrCodeBase64,checkoutUrl:o.payment?.checkoutUrl}};if(access)out.accessToken=access;return out}
(async()=>{await db.init();const server=http.createServer(main);server.listen(PORT,'0.0.0.0',()=>console.log(`LOTO15 v16.1 on :${PORT} database=${db.dbMode()}`));process.on('SIGTERM',async()=>{await db.close();server.close()});process.on('SIGINT',async()=>{await db.close();server.close()})})().catch(e=>{console.error(e);process.exit(1)});
